# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 23:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter video name', max_length=2000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('embed', models.TextField(blank=True, max_length=2000, null=True)),
                ('user', models.ForeignKey(help_text='a', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
