# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
