# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='json',
            field=models.TextField(max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='embed',
            field=models.TextField(blank=True, help_text='Enter the ID of Video', max_length=2000, null=True),
        ),
    ]
