# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20171019_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='json',
            field=models.TextField(max_length=500000, null=True),
        ),
    ]
