# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='adult',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
