# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_video_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='adult',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='json',
            field=models.TextField(blank=True, max_length=5000000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='processed',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
